export const TOKEN_CONTEXT_MENU_ORDER_ROLL_BULK_MACRO = 0;
export const TOKEN_CONTEXT_MENU_ORDER_HIT_DICE = 1;

export const TOKEN_CONTEXT_MENU_ORDER_CREATE_TOKEN_BY_URL = 2;
export const TOKEN_CONTEXT_MENU_ORDER_GET_TOKEN_IMAGE_URL = 3;

export const TOKEN_CONTEXT_MENU_ORDER_RESIZE_CUSTOM = 4;
export const TOKEN_CONTEXT_MENU_ORDER_RESIZE_FIT = 5;

export const TOKEN_CONTEXT_MENU_ORDER_NAME_COUNTER = 6;

